# Generated by Django 2.2.5 on 2020-04-12 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_remove_question_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answer_id',
        ),
    ]
